version: "3.7"

services:
     sql-server:
          image: mcr.microsoft.com/mssql/server
          container_name: banco

          ports:
               - "1717"
          environment:
               SA_PASSWORD: "Dockerau#!123"
               ACCEPT_EULA: "Y"
          networks: 
               - rede

     portal1:
          container_name: app1         
          hostname: app1
          build: 
               dockerfile: portal/Dockerfile
               context: .
          environment:
               - APP_NAME=APP1
          networks: 
               - rede

     portal2:
          container_name: app2              
          hostname: app2
          build: 
               dockerfile: portal/Dockerfile
               context: .
          environment:
               - APP_NAME=APP2        
          networks: 
               - rede

     portal3:
          container_name: app3
          hostname: app3
          build: 
               dockerfile: portal/Dockerfile
               context: .
          environment:
               - APP_NAME=APP3        
          networks: 
               - rede             

     portal4:
          container_name: app4
          hostname: app4
          build: 
               dockerfile: portal/Dockerfile
               context: .
          environment:
               - APP_NAME=APP4
          ports:
               - "8099"
          networks: 
               - rede                       

     nginx:
          build:
               dockerfile: ./config/Dockerfile
               context: .
          container_name: api-gateway
          ports:
               - "80:80"
               - "1717:1717"
               - "8099:8099"
          networks: 
               - rede
          depends_on:
               - "portal1"
               - "portal2"
               - "portal3"

networks:
    rede:    
        driver: bridge               