version: "3.7"

services:
     sql-server:
          image: mcr.microsoft.com/mssql/server
          container_name: banco
          environment:
               SA_PASSWORD: "Dockerau#!123"
               ACCEPT_EULA: "Y"
          networks: 
               - rede

     portal1:
          container_name: app1         
          hostname: app1
          build: 
               dockerfile: portal/Dockerfile
               context: .
          environment:
               - APP_NAME=APP1
          networks: 
               - rede

     portal2:
          container_name: app2              
          hostname: app2
          build: 
               dockerfile: portal/Dockerfile
               context: .
          environment:
               - APP_NAME=APP2        
          networks: 
               - rede

     portal3:
          container_name: app3
          hostname: app3
          build: 
               dockerfile: portal/Dockerfile
               context: .
          environment:
               - APP_NAME=APP3        
          networks: 
               - rede             

     portal4:
          container_name: app4
          hostname: app4
          build: 
               dockerfile: portal/Dockerfile
               context: .
          environment:
               - APP_NAME=APP4
          networks: 
               - rede                       

     nginx:
          build:
               dockerfile: ./config/Dockerfile
               context: .
          container_name: api-gateway
          ports:
               - "1717:1717"
               - "8080:8080"
               - "8099:8099"
               - "8180:8180"
          networks: 
               - rede
          depends_on:
               - "portal1"
               - "portal2"
               - "portal3"

     db: 
          image: mysql:5.7
          volumes:
               - db_data:/var/lib/mysql
          restart: always
          environment:
               MYSQL_ROOT_PASSWORD: wordpress
               MYSQL_DATABASE: wordpress
               MYSQL_USER: matheus
               MYSQL_PASSWORD: secret
          
          networks: 
               - rede
               
     wordpress:
          depends_on:
               - db
          image: wordpress:latest
          restart: always
          environment:
               WORDPRESS_DB_HOST: db:3306
               WORDPRESS_DB_USER: matheus
               WORDPRESS_DB_PASSWORD: secret
               WORDPRESS_DB_NAME: wordpress        
          networks: 
               - rede                      

networks:
    rede:    
        driver: bridge    

volumes:
     db_data: {}                   